package com.wizarpos.payment.aidl

import kotlinx.serialization.Serializable

@Serializable
data class GloablAidlResp(val		TransType:             String,
                          val		TransScheme:           String,
                          val		CallerName:            String,
                          val		TransIndexCode:        String,
                          val		 TransResult:          Boolean,
                          val		RespCode:              String,
                          val		RespDesc:              String,
                          val		CardNum:               String,
                          val		EntryMode:                Int,
                          val		ExpiryDate:            String,
                          val		CardBrand:             String,
                          val		TransAmount:           String,
                          val		OtherAmount:           String,
                          val		TipAmount:             String,
                          val		Balance:               String,
                          val		CurrencyCode:          String,
                          val		DccOriCurrencyCode:    String,
                          val		DccOriAmount:          String,
                          val		DccFee:                String,
                          val		DccExchangeRate:       String,
                          val		DccMarkUp:             String,
                          val		DccFooterText:         String,
                          val		TransDate:             String,
                          val		TransTime:             String,
                          val		CountryCode:           String,
                          val		MID:                   String,
                          val		TID:                   String,
                          val		MerchantName:          String,
                          val		MerchantAddress:       String,
                          val		TraceNum:              String,
                          val		TransID:               String,
                          val		InvoiceNum:            String,
                          val		RRN:                   String,
                          val		AuthCode:              String,
                          val		OriTransIndexCode:     String,
                          val		OriInvoiceNum:         String,
                          val		OriTransId:            String,
                          val		OriRrn:                String,
                          val		EmvAid:                String,
                          val		EmvAppName:            String,
                          val		EmvCryptogram:         String,
                          val		EmvTVR:                String)
